# @see https://circleci.com/orbs/registry/orb/circleci/aws-s3

version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  deploy-stg:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run:
          name: Cleanup for deploy
          command: |
            rm -rf .git
      - aws-s3/sync:
          from: .
          overwrite: true
          to: 's3://apps-stg.taxpolicycenter.org/features/presidential-candidate-tax-quiz'

  deploy-live:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run:
          name: Cleanup for deploy
          command: |
            rm -rf .git
      - aws-s3/sync:
          from: .
          overwrite: true
          to: 's3://apps.taxpolicycenter.org/features/presidential-candidate-tax-quiz'

workflows:
  version: 2
  aws-s3:
    jobs:
      - deploy-stg:
          filters:
            branches:
              only:
                - staging
  
      - deploy-live:
          filters:
            branches:
              only:
                - master